#!/usr/bin/env python

import sys
import argparse
from lib import jsonops

parser = argparse.ArgumentParser()
parser.add_argument("-r", "--reversed", action="store_false",
                    help="should array be reversed")
args = parser.parse_args()

line = sys.stdin.read()

try:
    json = jsonops.load_json(line)
except ValueError as e:
    print "Cannot parse json: " + str(e)
    sys.exit(1)

try:
    result = jsonops.array_sort(json, args.reversed)
except Exception as e:
    # More sophisticated exception processing to be added
    print "Error: " + str(e)
    sys.exit(1)
else:
    print unicode(result).encode('utf8')
